cd 3D-Diffusion-Policy

# python train.py --config-name=dp3.yaml \
#                             task=adroit_hammer \
#                             task.dataset.zarr_path=data/adroit_hammer_expert.zarr \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=10 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_bucket \
                            task.dataset.zarr_path=data/dexart_bucket_expert.zarr \
                            training.seed=0 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=10 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=adroit_door \
                            task.dataset.zarr_path=data/adroit_door_expert.zarr \
                            training.seed=0 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=adroit_pen \
                            task.dataset.zarr_path=data/adroit_pen_expert.zarr \
                            training.seed=0 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_bucket \
                            task.dataset.zarr_path=data/dexart_bucket_expert.zarr \
                            training.seed=0 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_faucet \
                            task.dataset.zarr_path=data/dexart_faucet_expert.zarr \
                            training.seed=0 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600                      

python train.py --config-name=dp3.yaml \
                            task=dexart_laptop \
                            task.dataset.zarr_path=data/dexart_laptop_expert.zarr \
                            training.seed=0 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_toilet \
                            task.dataset.zarr_path=data/dexart_toilet_expert.zarr \
                            training.seed=0 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=adroit_hammer \
                            task.dataset.zarr_path=data/adroit_hammer_expert.zarr \
                            training.seed=1 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=adroit_door \
                            task.dataset.zarr_path=data/adroit_door_expert.zarr \
                            training.seed=1 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=adroit_pen \
                            task.dataset.zarr_path=data/adroit_pen_expert.zarr \
                            training.seed=1 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_bucket \
                            task.dataset.zarr_path=data/dexart_bucket_expert.zarr \
                            training.seed=1 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_faucet \
                            task.dataset.zarr_path=data/dexart_faucet_expert.zarr \
                            training.seed=1 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600                      

python train.py --config-name=dp3.yaml \
                            task=dexart_laptop \
                            task.dataset.zarr_path=data/dexart_laptop_expert.zarr \
                            training.seed=1 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_toilet \
                            task.dataset.zarr_path=data/dexart_toilet_expert.zarr \
                            training.seed=1 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=adroit_hammer \
                            task.dataset.zarr_path=data/adroit_hammer_expert.zarr \
                            training.seed=2 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=adroit_door \
                            task.dataset.zarr_path=data/adroit_door_expert.zarr \
                            training.seed=2 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=adroit_pen \
                            task.dataset.zarr_path=data/adroit_pen_expert.zarr \
                            training.seed=2 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_bucket \
                            task.dataset.zarr_path=data/dexart_bucket_expert.zarr \
                            training.seed=2 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_faucet \
                            task.dataset.zarr_path=data/dexart_faucet_expert.zarr \
                            training.seed=2 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600                      

python train.py --config-name=dp3.yaml \
                            task=dexart_laptop \
                            task.dataset.zarr_path=data/dexart_laptop_expert.zarr \
                            training.seed=2 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=dexart_toilet \
                            task.dataset.zarr_path=data/dexart_toilet_expert.zarr \
                            training.seed=2 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=128 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600