cd 3D-Diffusion-Policy

python train.py --config-name=dp3.yaml \
                            task=robosuite_square \
                            task.dataset.zarr_path=data/robosuite_square.zarr \
                            task.env_runner.eval_episodes=50 \
                            training.seed=0 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=512 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=robosuite_square \
                            task.dataset.zarr_path=data/robosuite_square.zarr \
                            task.env_runner.eval_episodes=50 \
                            training.seed=1 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=512 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=robosuite_square \
                            task.dataset.zarr_path=data/robosuite_square.zarr \
                            task.env_runner.eval_episodes=50 \
                            training.seed=2 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=512 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=robosuite_can \
                            task.dataset.zarr_path=data/robosuite_can.zarr \
                            task.env_runner.eval_episodes=50 \
                            training.seed=0 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=512 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=robosuite_can \
                            task.dataset.zarr_path=data/robosuite_can.zarr \
                            task.env_runner.eval_episodes=50 \
                            training.seed=1 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=512 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

python train.py --config-name=dp3.yaml \
                            task=robosuite_can \
                            task.dataset.zarr_path=data/robosuite_can.zarr \
                            task.env_runner.eval_episodes=50 \
                            training.seed=2 \
                            training.num_epochs=3000 \
                            dataloader.batch_size=512 \
                            dataloader.num_workers=8 \
                            val_dataloader.num_workers=8 \
                            training.device="cuda" \
                            logging.mode=online \
                            checkpoint.save_ckpt=true \
                            training.rollout_every=600 \
                            training.val_every=4000 \
                            training.sample_every=4000 \
                            training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=robosuite_stack \
#                             task.dataset.zarr_path=data/robosuite_stack.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=224 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=4000 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=robosuite_stack \
#                             task.dataset.zarr_path=data/robosuite_stack.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=224 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=4000 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=robosuite_stack \
#                             task.dataset.zarr_path=data/robosuite_stack.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=224 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=4000 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=mimicgen_three_piece_assembly \
#                             task.dataset.zarr_path=data/mimicgen_assembly.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=512 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=mimicgen_stack_three \
#                             task.dataset.zarr_path=data/mimicgen_stack_three.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=512 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=mimicgen_three_piece_assembly \
#                             task.dataset.zarr_path=data/mimicgen_assembly.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=512 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=mimicgen_stack_three \
#                             task.dataset.zarr_path=data/mimicgen_stack_three.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=512 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=mimicgen_three_piece_assembly \
#                             task.dataset.zarr_path=data/mimicgen_assembly.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=512 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=mimicgen_stack_three \
#                             task.dataset.zarr_path=data/mimicgen_stack_three.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=512 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=adroit_hammer \
#                             task.dataset.zarr_path=data/adroit_hammer_expert.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=adroit_door \
#                             task.dataset.zarr_path=data/adroit_door_expert.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=adroit_pen \
#                             task.dataset.zarr_path=data/adroit_pen_expert.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=dexart_bucket \
#                             task.dataset.zarr_path=data/dexart_bucket_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=dexart_faucet \
#                             task.dataset.zarr_path=data/dexart_faucet_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600                      

# python train.py --config-name=dp3.yaml \
#                             task=dexart_laptop \
#                             task.dataset.zarr_path=data/dexart_laptop_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=dexart_toilet \
#                             task.dataset.zarr_path=data/dexart_toilet_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=0 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=adroit_hammer \
#                             task.dataset.zarr_path=data/adroit_hammer_expert.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=adroit_door \
#                             task.dataset.zarr_path=data/adroit_door_expert.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=adroit_pen \
#                             task.dataset.zarr_path=data/adroit_pen_expert.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=dexart_bucket \
#                             task.dataset.zarr_path=data/dexart_bucket_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=dexart_faucet \
#                             task.dataset.zarr_path=data/dexart_faucet_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600                      

# python train.py --config-name=dp3.yaml \
#                             task=dexart_laptop \
#                             task.dataset.zarr_path=data/dexart_laptop_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=dexart_toilet \
#                             task.dataset.zarr_path=data/dexart_toilet_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=1 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=adroit_hammer \
#                             task.dataset.zarr_path=data/adroit_hammer_expert.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=adroit_door \
#                             task.dataset.zarr_path=data/adroit_door_expert.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=adroit_pen \
#                             task.dataset.zarr_path=data/adroit_pen_expert.zarr \
#                             task.env_runner.eval_episodes=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=dexart_bucket \
#                             task.dataset.zarr_path=data/dexart_bucket_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=dexart_faucet \
#                             task.dataset.zarr_path=data/dexart_faucet_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600                      

# python train.py --config-name=dp3.yaml \
#                             task=dexart_laptop \
#                             task.dataset.zarr_path=data/dexart_laptop_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600

# python train.py --config-name=dp3.yaml \
#                             task=dexart_toilet \
#                             task.dataset.zarr_path=data/dexart_toilet_expert.zarr \
#                             task.env_runner.n_train=50 \
#                             training.seed=2 \
#                             training.num_epochs=3000 \
#                             dataloader.batch_size=128 \
#                             dataloader.num_workers=8 \
#                             val_dataloader.num_workers=8 \
#                             training.device="cuda" \
#                             logging.mode=online \
#                             checkpoint.save_ckpt=true \
#                             training.rollout_every=600 \
#                             training.val_every=4000 \
#                             training.sample_every=4000 \
#                             training.checkpoint_every=600